name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: arm64
          distribution: full
          variant: CS
          version: '9.1'

      - name: Link nemesis package
        run: raco pkg install --auto --batch --no-docs --link $GITHUB_WORKSPACE

      - name: Run tests
        run: raco test -p nemesis
